### ISSUE TITLE
WslToolbox crashes if docker is not running.

### ISSUE THREAD

**Issue by dembeck** [FalconNL93/WslToolbox#7]
## ISSUE

If docker desktop is not running, it does not show any installed distros, and if you hit "refresh" WslToolbox then exits silently.

If docker is running it does show installed distros and the refresh button works correctly.

## LOGS

- Below is a screenshot and content of ```./data/log.txt``` when WslToolbox is started when docker is not running.

```log
2023-02-01 13:13:54.771 -08:00 [Error] An UI exception has occurred: "The given key '' was not present in the dictionary."
System.Collections.Generic.KeyNotFoundException: The given key '' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at WslToolbox.Core.DistributionClass.DistributionState(String name, String output) in D:\a\WslToolbox\WslToolbox\WslToolbox.Core\DistributionClass.cs:line 100
   at WslToolbox.Core.DistributionClass.ListDistributions(String output) in D:\a\WslToolbox\WslToolbox\WslToolbox.Core\DistributionClass.cs:line 50
   at WslToolbox.Core.Commands.Service.ListServiceCommand.ListDistributions(Boolean withoutDocker) in D:\a\WslToolbox\WslToolbox\WslToolbox.Core\Commands\Service\ListServiceCommand.cs:line 15
   at WslToolbox.UI.Core.Services.DistributionService.ListDistributions() in D:\a\WslToolbox\WslToolbox\WslToolbox.UI.Core\Services\DistributionService.cs:line 46
   at WslToolbox.UI.ViewModels.DashboardViewModel.RefreshDistributions() in D:\a\WslToolbox\WslToolbox\WslToolbox.UI\ViewModels\DashboardViewModel.cs:line 152
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

<img width="677" alt="image" src="https://user-images.githubusercontent.com/9568447/216165117-dfc63ae2-b901-4209-869b-b5d477d5bfcc.png">

- Below is the content of ```./data/log.txt``` after selecting "refresh" in WslToolbox when docker is not running.

```log
2023-02-01 13:13:54.771 -08:00 [Error] An UI exception has occurred: "The given key '' was not present in the dictionary."
System.Collections.Generic.KeyNotFoundException: The given key '' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at WslToolbox.Core.DistributionClass.DistributionState(String name, String output) in D:\a\WslToolbox\WslToolbox\WslToolbox.Core\DistributionClass.cs:line 100
   at WslToolbox.Core.DistributionClass.ListDistributions(String output) in D:\a\WslToolbox\WslToolbox\WslToolbox.Core\DistributionClass.cs:line 50
   at WslToolbox.Core.Commands.Service.ListServiceCommand.ListDistributions(Boolean withoutDocker) in D:\a\WslToolbox\WslToolbox\WslToolbox.Core\Commands\Service\ListServiceCommand.cs:line 15
   at WslToolbox.UI.Core.Services.DistributionService.ListDistributions() in D:\a\WslToolbox\WslToolbox\WslToolbox.UI.Core\Services\DistributionService.cs:line 46
   at WslToolbox.UI.ViewModels.DashboardViewModel.RefreshDistributions() in D:\a\WslToolbox\WslToolbox\WslToolbox.UI\ViewModels\DashboardViewModel.cs:line 152
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
2023-02-01 13:18:26.252 -08:00 [Error] An UI exception has occurred: "The given key '' was not present in the dictionary."
System.Collections.Generic.KeyNotFoundException: The given key '' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at WslToolbox.Core.DistributionClass.DistributionState(String name, String output) in D:\a\WslToolbox\WslToolbox\WslToolbox.Core\DistributionClass.cs:line 100
   at WslToolbox.Core.DistributionClass.ListDistributions(String output) in D:\a\WslToolbox\WslToolbox\WslToolbox.Core\DistributionClass.cs:line 50
   at WslToolbox.Core.Commands.Service.ListServiceCommand.ListDistributions(Boolean withoutDocker) in D:\a\WslToolbox\WslToolbox\WslToolbox.Core\Commands\Service\ListServiceCommand.cs:line 15
   at WslToolbox.UI.Core.Services.DistributionService.ListDistributions() in D:\a\WslToolbox\WslToolbox\WslToolbox.UI.Core\Services\DistributionService.cs:line 46
   at WslToolbox.UI.ViewModels.DashboardViewModel.RefreshDistributions() in D:\a\WslToolbox\WslToolbox\WslToolbox.UI\ViewModels\DashboardViewModel.cs:line 152
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

- And this is from the Windows Event logs:

```xml
Log Name:      Application
Source:        Application Error
Date:          2023-02-01 1:18:26 PM
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:          Win11-01\MyUsername
Computer:      Win11-01
Description:
Faulting application name: toolbox.exe, version: 0.6.19.0, time stamp: 0x6387d353
Faulting module name: Microsoft.ui.xaml.dll, version: 3.0.0.2212, time stamp: 0x7dc2efab
Exception code: 0xc000027b
Fault offset: 0x00000000007cd8ec
Faulting process id: 0x0x6A54
Faulting application start time: 0x0x1D93682164D55AB
Faulting application path: C:\Users\MyUsername\AppData\Roaming\WSL Toolbox\toolbox.exe
Faulting module path: C:\Users\MyUsername\AppData\Roaming\WSL Toolbox\Microsoft.ui.xaml.dll
Report Id: 1b60a802-67b5-4e7e-b428-58b2101d3cc0
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2023-02-01T21:18:26.5294867Z" />
    <EventRecordID>7868</EventRecordID>
    <Correlation />
    <Execution ProcessID="29000" ThreadID="3424" />
    <Channel>Application</Channel>
    <Computer>Win11-01</Computer>
    <Security UserID="S-1-5-21-1633376866-3682407538-3970581744-1001" />
  </System>
  <EventData>
    <Data Name="AppName">toolbox.exe</Data>
    <Data Name="AppVersion">0.6.19.0</Data>
    <Data Name="AppTimeStamp">6387d353</Data>
    <Data Name="ModuleName">Microsoft.ui.xaml.dll</Data>
    <Data Name="ModuleVersion">3.0.0.2212</Data>
    <Data Name="ModuleTimeStamp">7dc2efab</Data>
    <Data Name="ExceptionCode">c000027b</Data>
    <Data Name="FaultingOffset">00000000007cd8ec</Data>
    <Data Name="ProcessId">0x6a54</Data>
    <Data Name="ProcessCreationTime">0x1d93682164d55ab</Data>
    <Data Name="AppPath">C:\Users\MyUsername\AppData\Roaming\WSL Toolbox\toolbox.exe</Data>
    <Data Name="ModulePath">C:\Users\MyUsername\AppData\Roaming\WSL Toolbox\Microsoft.ui.xaml.dll</Data>
    <Data Name="IntegratorReportId">1b60a802-67b5-4e7e-b428-58b2101d3cc0</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>


Log Name:      Application
Source:        Windows Error Reporting
Date:          2023-02-01 1:18:28 PM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      
User:          Win11-01\MyUsername
Computer:      Win11-01
Description:
Fault bucket 1752610233007211436, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: toolbox.exe
P2: 0.6.19.0
P3: 6387d353
P4: combase.dll
P5: 10.0.22621.900
P6: 622991f2
P7: 80131577
P8: 00000000000918bb
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.cc9c7bbf-e52d-4af5-bf1b-5e56fe7622e0.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c2ee0589-7842-4fe8-a46b-e6d51c81f28e.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5f6a8291-b04c-4415-abeb-f03a597118b0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.eafcd96c-90ee-408b-97ea-c3d3178328f6.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.33187a68-153a-4ec1-ac3e-141b5c2314f1.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_toolbox.exe_6116aa9fc4d8551469e23433bacc8963b4a07a_38d34b14_b6501b18-b52c-433d-90e0-fc4d8728647a

Analysis symbol: 
Rechecking for solution: 0
Report Id: 1b60a802-67b5-4e7e-b428-58b2101d3cc0
Report Status: 268435456
Hashed bucket: 4c7fcb7df4e60f2df85285b8a01c03ac
Cab Guid: 0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" Guid="{0ead09bd-2157-539a-8d6d-c87f95b64d70}" />
    <EventID>1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2023-02-01T21:18:28.9088195Z" />
    <EventRecordID>7869</EventRecordID>
    <Correlation />
    <Execution ProcessID="29000" ThreadID="3424" />
    <Channel>Application</Channel>
    <Computer>Win11-01</Computer>
    <Security UserID="S-1-5-21-1633376866-3682407538-3970581744-1001" />
  </System>
  <EventData>
    <Data Name="Bucket">1752610233007211436</Data>
    <Data Name="BucketType">4</Data>
    <Data Name="EventName">APPCRASH</Data>
    <Data Name="Response">Not available</Data>
    <Data Name="CabId">0</Data>
    <Data Name="P1">toolbox.exe</Data>
    <Data Name="P2">0.6.19.0</Data>
    <Data Name="P3">6387d353</Data>
    <Data Name="P4">combase.dll</Data>
    <Data Name="P5">10.0.22621.900</Data>
    <Data Name="P6">622991f2</Data>
    <Data Name="P7">80131577</Data>
    <Data Name="P8">00000000000918bb</Data>
    <Data Name="P9">
    </Data>
    <Data Name="P10">
    </Data>
    <Data Name="AttachedFiles">
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.cc9c7bbf-e52d-4af5-bf1b-5e56fe7622e0.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c2ee0589-7842-4fe8-a46b-e6d51c81f28e.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5f6a8291-b04c-4415-abeb-f03a597118b0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.eafcd96c-90ee-408b-97ea-c3d3178328f6.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.33187a68-153a-4ec1-ac3e-141b5c2314f1.tmp.xml</Data>
    <Data Name="StorePath">\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_toolbox.exe_6116aa9fc4d8551469e23433bacc8963b4a07a_38d34b14_b6501b18-b52c-433d-90e0-fc4d8728647a</Data>
    <Data Name="AnalysisSymbol">
    </Data>
    <Data Name="Rechecking">0</Data>
    <Data Name="ReportId">1b60a802-67b5-4e7e-b428-58b2101d3cc0</Data>
    <Data Name="ReportStatus">268435456</Data>
    <Data Name="HashedBucket">4c7fcb7df4e60f2df85285b8a01c03ac</Data>
    <Data Name="CabGuid">0</Data>
  </EventData>
</Event>
```

**Comment by FalconNL93** [comment]
Thanks for reporting the issue. It will be fixed in the next version.

**Comment by FalconNL93** [comment]
Issue fixed in develop. Will be in the next version :)
